parameters:
  - name: WORKSPACE_NAME
    displayName: Workspace name to conduct tests?
    type: string
    # Set the default value to the name of the my workspace
    default: 'Fabric DataOps Build'
  - name: DATASET_IDS
    displayName: If there is a set of datasets you would like tested, please provide comma-delimited list of GUIDs.
    type: string
    default: ' '

schedules:
- cron: 0 */6 * * *
  displayName: Every 6 hours
  branches:
    include:
      - development
      - test
      - main
  always: True

# Explicitly disable the azure devops default of yaml pipelines having a ci trigger enabled for all branches
trigger: none

pool:
  vmimage: 'windows-latest'

variables:
  # Variable group with configuration
  - group: TestingCredentials
  - name: 'WORKSPACE_NAME'
    value: '${{ parameters.WORKSPACE_NAME }}'
  - name: 'DATASET_IDS'
    value: '${{ parameters.DATASET_IDS}}'

jobs:
- job: Job_1
  displayName: Automated Job for the Dqv Deployment and Testing Pattern
  steps:
  - checkout: self
    fetchDepth: 0
  - task: PowerShell@2
    displayName: Conduct Testing
    env:
      PASSWORD_OR_CLIENTSECRET: $(PASSWORD_OR_CLIENTSECRET) # Maps the secret variable
    inputs:
      pwsh: true
      filePath: PipelineScripts/Run-DqvDeployTestingPattern.ps1
      failOnStderr: true
