parameters:
  - name: WORKSPACE_NAME
    displayName: Workspace name to conduct tests?
    type: string
    default: ''
  - name: DATASET_IDS
    displayName: If there is a set of datasets you would like tested, please provide comma-delimited list of GUIDs.
    type: string
    default: ' '

schedules:
- cron: 0 */6 * * *
  displayName: Every 6 hours
  branches:
    include:
      - development
      - test
      - main
  always: True

pool:
  vmimage: 'windows-latest'

variables:
  # Variable group with configuration
  - group: TestingCredentials
  - name: 'WORKSPACE_NAME'
    value: '${{ parameters.WORKSPACE_NAME }}'
  - name: 'DATASET_IDS'
    value: '${{ parameters.DATASET_IDS}}'

jobs:
- job: Job_1
  displayName: Automated Testing Job
  steps:
  - checkout: self
    fetchDepth: 0
  - task: PowerShell@2
    displayName: Install Dependencies
    inputs:
      pwsh: true
      targetType: inline
      script: |
        # ---------- Check if PowerShell Modules are Installed ---------- #
        # ---------- Download Modules ------------- #
        # Create a new directory in the current location
        if((Test-Path -path ".\modules") -eq $false){
            New-Item -Name "modules" -Type Directory
        }

        # For each url download and install in module folder
        @("https://raw.githubusercontent.com/kerski/fabric-dataops-patterns/development/DAX%20Query%20View%20Testing%20Pattern/modules/Invoke-DQVTesting.psm1",
          "https://raw.githubusercontent.com/kerski/fabric-dataops-patterns/development/DAX%20Query%20View%20Testing%20Pattern/modules/Invoke-DQVTesting.psd1"
          ) |% {
            Invoke-WebRequest -Uri $_ -OutFile ".\modules\$(Split-Path $_ -Leaf)"
        }     
  - task: PowerShell@2
    displayName: Conduct Testing
    env:
      PASSWORD_OR_CLIENTSECRET: $(PASSWORD_OR_CLIENTSECRET) # Maps the secret variable
    inputs:
      pwsh: true
      failOnStderr: true
      targetType: inline
      script: |             
        # Import Invoke-DQVTesting
        Import-Module ".\modules\Invoke-DQVTesting.psm1" -Force          

        $secret = ${env:PASSWORD_OR_CLIENTSECRET} | ConvertTo-SecureString -AsPlainText -Force
        $credentials = [System.Management.Automation.PSCredential]::new("${env:USERNAME_OR_CLIENTID}",$secret)                  

        # Check if specific datasets need to be tested
        $lengthCheck = "${env:DATASET_IDS}".Trim()
        if($lengthCheck -gt 0){
          $datasetsToTest = "${env:DATASET_IDS}".Trim() -split ','
        }else{
          $datasetsToTest = @()
        }

        # Run tests
        Invoke-DQVTesting -WorkspaceName "${env:WORKSPACE_NAME}" `
                        -Credential $credentials `
                        -TenantId "${env:TENANT_ID}" `
                        -DatasetId $datasetsToTest `
                        -LogOutput "ADO"